version: '3'

services:
  chatgpt-java:
    image: zhouhuabo/tl-chatgpt-java:0.1
    container_name: tl-chatgpt-java
    ports:
      - 8000:8080
    command: sh -c "java -jar /work/app.jar"
    environment:
      MAX_TOKENS: 4096
      TEMPERATURE: 0.9
      API_KEY: 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

    networks:
      main:
        aliases:
          - tl-chatgpt-java
#  app:
#    image: zhouhuabo/chatgpt-web:v1.1
#    ports:
#      - 80:80
#    networks:
#      main:
#        aliases:
#          - chatgpt-web
networks:
  main:
