server:
  port: 18080

# chatgpt 设置
chatgpt:
  # 默认的Token长度
  max_tokens: ${MAX_TOKENS:512}
  # 尝试将值设为 0.9 以获得更有创意的回复，将值设为 0 以获得具有明确答案的回复
  temperature: ${TEMPERATURE:0.6}
  # 默认的AI模型，gpt-3.5-turbo or gpt-3.5-turbo-0301	，区别：https://platform.openai.com/docs/models/gpt-3-5
  model: gpt-3.5-turbo
  # 多个Key用,分割
  api_key: ${API_KEY:}
  # 默认主机，如果代理的话，就配置代理的主机
  api_host: https://api.openai.com/

# 系统设置
system:
  # 默认携带上下文条数
  context_num: ${CONTEXT_NUM:10}
  # 是否使用内置 key
  use_internal_key: ${USE_INTERNAL_KEY:true}
